name: CD - Deploy to Railway

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to Railway
      run: |
        curl -X POST ${{ secrets.RAILWAY_DEPLOY_HOOK }}
